ui_print " "
ui_print "This module is Xiaomi Mi MIX 3 (Perseus or Andromeda)'s"
ui_print "VOICE_ASSIST button replaces to F1 button."
ui_print " "
ui_print "Installation succeed."
ui_print " "
ui_print "You can execute any command"
ui_print "with the Button Mapper App."
ui_print " "
ui_print "You can also extract this zip file"
ui_print "and assign it to a different key before installation."
ui_print " "
ui_print "Thank you!"
ui_print " "
